# Generated by Django 4.0 on 2022-02-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_image',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='images')),
            ],
        ),
    ]
