# Generated by Django 4.0 on 2022-02-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_image',
            old_name='firstname',
            new_name='fullname',
        ),
    ]
